language: php

# cache
cache:
    directories:
        - vendor

# php versions
matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2

# test only master (+ pull requests)
branches:
  only:
    - master

before_install:
    - phpenv config-add travis.php.ini

# install dependencies
install:
    - travis_wait composer install

# execute phpunit as the script command
script:
  - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml.dist --coverage-clover=coverage.xml

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30

# we don't need sudo
sudo: false

# send coverage to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
